const produtos = [
    {
        id: "adipotide-5mg",
        nome: "Adipotide-5mg",
        imagem: "./img/adipotide-5mg.jpeg",
        descricaoCurta: "Adipotide é um análogo sintético da proteína, age como um agonista dos receptores GPR119 e GPR55.",
        descricaoCompleta: "Adipotide é um análogo sintético da proteína, age como um agonista dos receptores GPR119 e GPR55, ambos envolvidos no metabolismo de lipídeos e carboidratos. O medicamento foi desenvolvido para o tratamento da obesidade e da diabetes mellitus tipo 2, e tem demonstrado resultados promissores em estudos clínicos.",
        categoria: "Perda de Peso",
        dosagem: "5mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "aod-9604-5mg",
        nome: "AOD-9604-5mg",
        imagem: "./img/aod-9604-5mg.jpeg",
        descricaoCurta: "Fragmento do hormônio do crescimento humano que estimula a lipólise e inibe a lipogênese.",
        descricaoCompleta: "Fragmento do hormônio do crescimento humano que estimula a lipólise e inibe a lipogênese. Utilizado para perda de peso e melhora da composição corporal. O AOD-9604 é o fragmento 176-191 do hormônio do crescimento humano, responsável pela atividade lipolítica.",
        categoria: "Perda de Peso",
        dosagem: "5mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "cjc-1295-with-dac-5mg",
        nome: "CJC-1295 with DAC-5mg",
        imagem: "./img/cjc-1295-with-dac-5mg.jpeg",
        descricaoCurta: "Análogo do hormônio liberador de hormônio do crescimento (GHRH).",
        descricaoCompleta: "Análogo do hormônio liberador de hormônio do crescimento (GHRH). Estimula a liberação sustentada de GH, promovendo sono, recuperação muscular e queima de gordura. O DAC (Drug Affinity Complex) prolonga a meia-vida do composto para até 6-8 dias.",
        categoria: "Hormônio do Crescimento",
        dosagem: "5mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "cjc-1295-without-dac-10mg",
        nome: "CJC-1295 without DAC-10mg",
        imagem: "./img/cjc-1295-without-dac-10mg.jpeg",
        descricaoCurta: "Versão de ação rápida do CJC-1295 sem DAC.",
        descricaoCompleta: "Versão de ação rápida do CJC-1295 sem DAC. Estimula pulsos de GH com meia-vida mais curta, ideal para uso noturno e recuperação muscular. Sem o DAC, o composto tem meia-vida de aproximadamente 30 minutos.",
        categoria: "Hormônio do Crescimento",
        dosagem: "10mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "follistatin-1mg",
        nome: "Follistatin-1mg",
        imagem: "./img/follistatin-1mg.jpeg",
        descricaoCurta: "Proteína que regula negativamente o TGF-beta.",
        descricaoCompleta: "Proteína que regula negativamente o TGF-beta. Promove crescimento muscular ao inibir a miostatina, sendo estudada para sarcopenia e distrofia muscular. A Follistatin é uma proteína natural que regula negativamente several members of the TGF-beta superfamily.",
        categoria: "Crescimento Muscular",
        dosagem: "1mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "ghk-cu-100mg",
        nome: "GHK-Cu-100mg",
        imagem: "./img/ghk-cu-100mg.jpeg",
        descricaoCurta: "Complexo de cobre-tripeptídeo com propriedades regenerativas.",
        descricaoCompleta: "Complexo de cobre-tripeptídeo com propriedades regenerativas. Estimula a síntese de colágeno, elastina e glicosaminoglicanos, sendo utilizado em anti-aging e cicatrização. O GHK-Cu é um naturally occurring copper complex with the tripeptide glycyl-L-histidyl-L-lysine.",
        categoria: "Anti-aging",
        dosagem: "100mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "glow-70mg",
        nome: "Glow-70mg",
        imagem: "./img/glow-70mg.jpeg",
        descricaoCurta: "Peptídeo bioativo para rejuvenescimento cutâneo.",
        descricaoCompleta: "Peptídeo bioativo para rejuvenescimento cutâneo. Melhora a elasticidade, hidratação e luminosidade da pele, promovendo um aspecto mais jovem e saudável. O Glow é uma formulação exclusiva de peptídeos bioativos para skincare.",
        categoria: "Anti-aging",
        dosagem: "70mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "hcg-10000ui",
        nome: "HCG-10000UI",
        imagem: "./img/hcg-10000ui.jpeg",
        descricaoCurta: "Gonadotrofina coriônica humana.",
        descricaoCompleta: "Gonadotrofina coriônica humana. Utilizada para estimular a produção de testosterona, preservar a fertilidade e auxiliar na perda de peso em protocolos hormonais. O HCG é uma hormona glicoproteica produzida durante a gravidez.",
        categoria: "Hormônio",
        dosagem: "10000UI",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "hgh-fragment-176-191-5mg",
        nome: "HGH Fragment 176-191-5mg",
        imagem: "./img/hgh-fragment-176-191-5mg.jpeg",
        descricaoCurta: "Fragmento ativo do hormônio do crescimento focado em lipólise.",
        descricaoCompleta: "Fragmento ativo do hormônio do crescimento focado em lipólise. Promove queima de gordura sem os efeitos de crescimento de tecidos, sendo ideal para composição corporal. Este fragmento é a parte do HGH responsável pela atividade lipolítica.",
        categoria: "Perda de Peso",
        dosagem: "5mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "igf-1-lr3-1mg",
        nome: "IGF-1 LR3-1mg",
        imagem: "./img/igf-1-lr3-1mg.jpeg",
        descricaoCurta: "Fator de crescimento insulínico tipo 1 com meia-vida prolongada.",
        descricaoCompleta: "Fator de crescimento insulínico tipo 1 com meia-vida prolongada. Estimula hiperplasia muscular e regeneração tecidual, sendo utilizado em protocolos de performance. O LR3 (Long R3) é uma forma modificada com meia-vida de 8-12 horas.",
        categoria: "Crescimento Muscular",
        dosagem: "1mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "ipamorelin-10mg",
        nome: "Ipamorelin-10mg",
        imagem: "./img/ipamorelin-10mg.jpeg",
        descricaoCurta: "Secretagogo de GH seletivo que estimula a liberação natural de hormônio do crescimento.",
        descricaoCompleta: "Secretagogo de GH seletivo que estimula a liberação natural de hormônio do crescimento. Melhora sono, recuperação e composição corporal sem afetar cortisol. O Ipamorelin é um pentapeptídeo que seletivamente estimula a liberação de GH.",
        categoria: "Hormônio do Crescimento",
        dosagem: "10mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "klow-80mg",
        nome: "Klow-80mg",
        imagem: "./img/klow-80mg.jpeg",
        descricaoCurta: "Peptídeo com ação lipolítica e anti-inflamatória.",
        descricaoCompleta: "Peptídeo com ação lipolítica e anti-inflamatória. Auxilia na redução de gordura localizada e melhora da sensibilidade insulínica. O Klow é uma formulação avançada para auxílio na composição corporal.",
        categoria: "Perda de Peso",
        dosagem: "80mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "lemon-bottle-10mg",
        nome: "Lemon Bottle-10mg",
        imagem: "./img/lemon-bottle-10mg.jpeg",
        descricaoCurta: "Fórmula lipolítica para aplicação tópica.",
        descricaoCompleta: "Fórmula lipolítica para aplicação tópica. Combina aminoácidos e vitaminas para acelerar a queima de gordura em áreas localizadas. O Lemon Bottle é uma solução lipolítica de alta concentração.",
        categoria: "Perda de Peso",
        dosagem: "10mg",
        formaApresentacao: "Solução para aplicação tópica",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "mots-c-40mg",
        nome: "MOTS-c-40mg",
        imagem: "./img/mots-c-40mg.jpeg",
        descricaoCurta: "Peptídeo mitocondrial que regula o metabolismo energético.",
        descricaoCompleta: "Peptídeo mitocondrial que regula o metabolismo energético. Melhora a sensibilidade insulínica, a queima de gordura e a performance física. O MOTS-c é um peptídeo mitocondrial derivado do genoma mitocondrial.",
        categoria: "Metabolismo",
        dosagem: "40mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "pinealon-20mg",
        nome: "Pinealon-20mg",
        imagem: "./img/pinealon-20mg.jpeg",
        descricaoCurta: "Peptídeo citoprotetor com ação no sistema nervoso central.",
        descricaoCompleta: "Peptídeo citoprotetor com ação no sistema nervoso central. Melhora cognição, memória e proteção neuronal, sendo estudado para neurodegeneração. O Pinealon é um dipeptídeo que penetra a barreira hematoencefálica.",
        categoria: "Saúde Cognitiva",
        dosagem: "20mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "pt-141-10mg",
        nome: "PT-141-10mg",
        imagem: "./img/pt-141-10mg.jpeg",
        descricaoCurta: "Agonista seletivo do receptor MC3R.",
        descricaoCompleta: "Agonista seletivo do receptor MC3R. Utilizado para tratamento de disfunção sexual, aumentando a libido e a excitação em ambos os sexos. O PT-141 (Bremelanotide) atua diretamente no sistema nervoso central.",
        categoria: "Saúde Sexual",
        dosagem: "10mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "retatrutide-60mg",
        nome: "Retatrutide-60mg",
        imagem: "./img/retatrutide-60mg.jpeg",
        descricaoCurta: "Agonista tripla de receptores GLP-1, GIP e glucagon.",
        descricaoCompleta: "Agonista tripla de receptores GLP-1, GIP e glucagon. Potente promotor de perda de peso e melhora metabólica, sendo um dos compostos mais promissores em desenvolvimento. A Retatrutide atua em três vias metabólicas simultaneamente.",
        categoria: "Perda de Peso",
        dosagem: "60mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "slu-pp-332-5mg",
        nome: "SLU-PP-332-5mg",
        imagem: "./img/slu-pp-332-5mg.jpeg",
        descricaoCurta: "Agonista do receptor ERRγ que estimula a biogênese mitocondrial.",
        descricaoCompleta: "Agonista do receptor ERRγ que estimula a biogênese mitocondrial. Melhora a resistência muscular e a capacidade oxidativa, sendo estudado para envelhecimento e performance. O SLU-PP-332 ativa vias de extensão da longevidade.",
        categoria: "Longevidade",
        dosagem: "5mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "ss-31-10mg",
        nome: "SS-31-10mg",
        imagem: "./img/ss-31-10mg.jpeg",
        descricaoCurta: "Peptídeo mitocondrial que protege contra o estresse oxidativo.",
        descricaoCompleta: "Peptídeo mitocondrial que protege contra o estresse oxidativo. Melhora a função mitocondrial, sendo estudado para doenças neurodegenerativas e envelhecimento. O SS-31 (Elamipretide) seleta acima da membrana mitocondrial interna.",
        categoria: "Saúde Mitochondrial",
        dosagem: "10mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "tesamorelin-10mg",
        nome: "Tesamorelin-10mg",
        imagem: "./img/tesamorelin-10mg.jpeg",
        descricaoCurta: "Análogo do GHRH aprovado para redução de gordura abdominal em pacientes com HIV.",
        descricaoCompleta: "Análogo do GHRH aprovado para redução de gordura abdominal em pacientes com HIV. Estimula a liberação de GH de forma fisiológica. A Tesamorelin é aprovada pela FDA para lipodistrofia associada ao HIV.",
        categoria: "Hormônio do Crescimento",
        dosagem: "10mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "thymosin-alpha1-10mg",
        nome: "Thymosin Alpha-1-10mg",
        imagem: "./img/thymosin-alpha1-10mg.jpeg",
        descricaoCurta: "Peptídeo imunomodulador derivado do timo.",
        descricaoCompleta: "Peptídeo imunomodulador derivado do timo. Fortalece a resposta imunológica, sendo utilizado em infecções virais, câncer e como coadjuvante vacinal. A Thymosin Alpha-1 é um peptídeo de 28 aminoácidos naturally present no timo.",
        categoria: "Sistema Imunológico",
        dosagem: "10mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "tirzepatide-15mg",
        nome: "Tirzepatide-15mg",
        imagem: "./img/tirzepatide-15mg.jpeg",
        descricaoCurta: "Agonista duplo de receptores GLP-1 e GIP.",
        descricaoCompleta: "Agonista duplo de receptores GLP-1 e GIP. Excelente resultado em perda de peso e controle glicêmico, sendo uma das opções mais eficazes para obesidade e diabetes tipo 2. A Tirzepatide é um peptídeo sintético de 39 aminoácidos.",
        categoria: "Perda de Peso",
        dosagem: "15mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    },
    {
        id: "tirzepatide-60mg",
        nome: "Tirzepatide-60mg",
        imagem: "./img/tirzepatide-60mg.jpeg",
        descricaoCurta: "Apresentação de maior dose do Tirzepatide.",
        descricaoCompleta: "Apresentação de maior dose do Tirzepatide. Agonista duplo GLP-1/GIP para protocolos avançados de perda de peso e controle metabólico. Esta apresentação permite dosagens mais altas para pacientes que necessitam de tratamento intensivo.",
        categoria: "Perda de Peso",
        dosagem: "60mg",
        formaApresentacao: "Pó liofilizado para reconstituição",
        armazenamento: "Refrigerado (2-8°C)",
        prazoValidade: "24 meses"
    }
];
